language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: heroku
  api_key:
    secure: sFLq2tOPlj82SYCNdqXg1bwiIjsyQHEkG62XUjDjUQhfb93ZCNB6OYRAyVlcBFFL+pSmtU0BQrNA108V7eeDKeUrE2Od+wQI7qyscpSU/TPgep31Etdr6Hl9EzB0leKcooU8iLesQMmprq8XSFdi8Nare93H79ULigZBl0ARjumvsHXsJGMmJTSjlS7C4n2avhfRkeZNNh1RfToluSZLhN2qLXx9xIrtW+pXQ0i6JlJPGd9a1MulXw5HzcB1oQuHeBFSLVwVLvjNDzo/deBiRu4HMGTqzU6p099IFekBHtU9M1mgmZeKL+POFqTEQUBY9UMegeLAt+S+nnf/yY65hMTkn9teKhNFHueIxz/+PgZbxCMXV1KxvEG0rWbdw3G48WlXqG+9vP2/1mYM3lOgd7lLoSL1X11aFG9BSDo1OPVzus7ZDrjBC/Nyylya8UYwZKJdOjPlvkyW0QesbODlzrWZpksgFwjm3NkQq4x4s2Ncv71foRqrmeItJOuchi8XX5eYcpDqxHX0eIs8ECyk455AH7d5nwCROsPD5rAk2/iVN7ZTTECUSGXgfLBIiBh8Xfk7nL+S4QkfWKchyiGCED+COLmqkbNNO3hVj/WIY+0oFd2CSPNRSYQ7ClCEjhXqr6xTflvxpthGSGiKsqpB2TyV3uAyNptWZ2lL6mmsZwg=
  run: "python main.py"